#!/Users/ark3/datawire/telepresence/virtualenv/bin/python3

from getpass import getuser
import json
import os
import socket
import sys


def main():
    # Connect
    sock = socket.socket(socket.AF_UNIX)
    sockname = "/var/run/playpen.socket"
    try:
        sock.connect(sockname)
    except FileNotFoundError as exc:
        print(f"Connect to {sockname} failed: {exc}")
        exit("playpen: Could not connect to PlaypenD. Is it running?")

    # Send request
    request = dict(
        env=dict(os.environ),
        user=getuser(),
        args=sys.argv[1:],
        api=1,
    )
    out = sock.makefile(mode="w", buffering=1, encoding="utf8")
    json.dump(request, out, indent=2)
    out.close()
    sock.shutdown(socket.SHUT_WR)

    # Display response as it comes in
    token = "-- exit "
    in_ = sock.makefile(mode="r", encoding="utf8")
    for line in in_:
        if line.startswith(token):
            code_str = line.rstrip()[len(token):]
            try:
                code = int(code_str)
            except ValueError:
                code = f"Bad exit code from server: {repr(code_str)}"
            exit(code)
        print(line.rstrip())
    in_.close()
    sock.close()


if __name__ == "__main__":
    main()
